{% set version = "0.2.17" %}

package:
  name: nh3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nh3/nh3-{{ version }}.tar.gz
  sha256: 40d0741a19c3d645e54efba71cb0d8c475b59135c1e3c580f879ad5514cbf028

build:
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.0,<2.0                  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - nh3
  commands:
    - pip check
    - pytest -vv --cov=nh3 --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/nh3
  summary: Ammonia HTML sanitizer Python binding
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/messense/nh3

extra:
  recipe-maintainers:
    - bollwyvl
