{% set version = "0.2.19" %}

package:
  name: nh3
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nh3/nh3-{{ version }}.tar.gz
  sha256: 790056b54c068ff8dceb443eaefb696b84beff58cca6c07afd754d17692a4804

build:
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.0,<2.0                  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - nh3
  commands:
    - pip check
    - coverage run --source=nh3 --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=83
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://github.com/messense/nh3
  summary: Python binding to Ammonia HTML sanitizer Rust crate
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://nh3.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
