{% set version = "0.2.14" %}

package:
  name: nh3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nh3/nh3-{{ version }}.tar.gz
  sha256: a0c509894fd4dccdff557068e5074999ae3b75f4c5a2d6fb5415e782e25679c4

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - nh3
  commands:
    - pip check
    - pytest -vv --cov=nh3 --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/nh3
  summary: Ammonia HTML sanitizer Python binding
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/messense/nh3

extra:
  recipe-maintainers:
    - bollwyvl
