# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.0"
  maturin_min: "1.0"
  maturin_max: "2.0"

package:
  name: nh3
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nh3/nh3-${{ version }}.tar.gz
  sha256: d8ba24cb31525492ea71b6aac11a4adac91d828aadeff7c4586541bf5dc34d2f

build:
  number: 1
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true
  script:
    file: build-nh3

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - if: unix
      then:
        - ${{ compiler("c") }}
  host:
    - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - pip
    - python
    - python-abi3
  run:
    - python
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: nh3
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=nh3 --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=83

about:
  summary: Python binding to Ammonia HTML sanitizer Rust crate
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/messense/nh3
  documentation: https://nh3.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
